### ISSUE TITLE
Interaction with real mouse buttons

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warpd#10]
I'm using `warp` with a pair of [Twiddlers](https://twiddler.tekgear.com/) which have the world's worst 8 directional joystick for a pointer (hence my interest in this program). The mouse buttons are fine though - it'd be nice if I could use those directly, but at present `warp` both ignores them and blocks them from functioning.

I could see making `warp` aware of real mouse movement as well, but that's probably a pain in the butt and not really necessary for my use case, as I'm hoping to stop using the Twiddler's physical joysticks entirely (they're *really* terrible)

**Comment by rvaiya** [comment]
Interesting. X treats mouse buttons and key presses differently so I would have to add a pointer grab in order to achieve this. Doing so adds the potential for another class of bugs and is antithetical to the spirit of a keyboard driven mouse program anyway.  Isn't it possible to remap the mouse buttons on your twiddler to send key events?

**Comment by wearpants** [comment]
If we can do the mouse mode as described in #5, this isn't necessary - I'd actually prefer that, as it'd give me 3 more top level keysyms (that I could then overload as buttons under warp activation)
