### ISSUE TITLE
Transparent backgound mask when mouse mode toggle on

### ISSUE THREAD

**Issue by LintaoAmons** [rvaiya/warpd#110]
Sometimes the small red dot is not significant to let me realize that I have already toggled on the mouse model.
And sometimes I accidentally quit the mouse mode already but didn't realize, still typing but the char goes into the wrong places.

So may a configurable background color mask will be nice to hint me that I'm in or not in the mouse model.

**Comment by rvaiya** [comment]
You can already configure the size and color of the cursor. See the man page for details

**Comment by rvaiya** [comment]
>  In my opinion, this could be a nice gimmick but with limited practical use

I am inclined to agree with you, but practical considerations aside, there are also implementation issues. On most platforms it isn't possible to draw over/tint the entire screen without obscuring the pointer. This is part of the reason the pointer is located to the left of the visual indicator since it allows applications to properly track the pointer position so you can do things like scrub a youtube video and still have the appropriate hover based UI clues pop up.

> as one should only activate a warpd mode with a specific purpose (clicking or selecting something) and then exit it once this purpose has achieved.

Actually a common pattern of use for me is to leave warpd running whilst browsing. The trick is to become accustomed to using `e` and `r` for scrolling. Usually you will want to click on a UI element before entering some text at which point you can do something like  `x <hint> n` to click on the input element and exit warpd.

**Comment by LintaoAmons** [comment]
> So in the unlikely case you never heard about this, I can warmly recommend trying it out.

I never heard about this `qutebrowser`, sound's interesting. I use firefox with `surfingkey` which I think is better than vimium. Cause it proved the `v` mode to select the text in the website and copy the context selected as vim does. Also, I didn't use wrapd in the browser either. But `waprd` is super smooth and I do use it `with a specific purpose (clicking or selecting something) and then exit it once this purpose has been achieved`.

I think it will be good to have something to hint the user that you are in `warpd` mode as easy as possible. The user doesn't need to `find` the hint but just look at any place on the screen, then knows the mode has been triggered.

By the way, I use only `activation_key` to trigger the mode, if I want the hint, I press `x` after go into the mode.

**Comment by rvaiya** [comment]
> Both mentioned solutions give you webpage specific hint mode, where hints are only shown above clickable
> elements, and qutebrowser adds complete keyboard control of the browser itself
> (vimium sometimes can't do this due to plugin sandboxing). 

I actually migrated away from vimium to warpd (which I didn't anticipate) for web browsing because it loads a lot faster and you can start positioning before the DOM has finished loading.

> So in the unlikely case you never heard about this, I can warmly recommend trying it out.

On the contrary, hint mode was inspired by vimperator :P.

> I think it will be good to have something to hint the user that you are in
> warpd mode as easy as possible. The user doesn't need to find the hint but just
> look at any place on the screen, then knows the mode has been triggered.

I would recommend experimenting with a different cursor size/color. The cursor should be relatively easy to see.

> By the way, I use only activation_key to trigger the mode, if I want the hint,
> I press x after go into the mode.

+1

I'm closing this for now. Feel free to open another issue if you feel strongly about it.
