### ISSUE TITLE
feature request: hint mode for history stack and generic configurable coordinate sets

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warpd#111]
Apologies in advance for this very long post. Beneath the issue described in the title, it actually contains a smorgasbord of ideas touching many parts of warpd. As these are all connected to implementing some sort of generic hint mode, I decided to put them into a single feature request.

### Hint mode for the history stack

I recently started experimenting with the history stack and thought about ways to make it more usable. Then an idea came to my mind which should be very useful: How about a hint mode for the history stack? In other words, an action which would mark all points in the history stack on the screen with a character which could then be navigated to? Several problems would have to be addressed:

*hint character assignment*
Thinking about typical use cases, where one already has several interesting screen points in history and then successively adds to the stack (in fact, what I will describe is no longer a stack from a programmer's point of view, but let's ignore that for the moment), the hint character(s) assigned to a specific point should not change throughout its entire life in the stack. Also, depending on the maximal size of the history stack and configured hint characters, the length of a character sequence assigned to a point should be flexible. For example, indicating 26 hint characters (say a-z) and a maximal history stack size of 52, two characters per point are needed, whereas a stack size of 20 would only require one. However, from a user perspective it would be very inefficient to introduce two characters per point for a maximal stack size of 30. Instead, it would suffice to complement the first four characters with a second one, once the actual stack size exceeds 26. In other words: If there are already 26 points on the stack (assigned all 26 characters a-z), upon adding the 27th point, the character of the first point would change from `a` to `aa`, while the 27th point would be assigned characters `ab`. Note how from a user perspective, typing `a` would still include the first point in the narrowed down selection set.

*replacement of points in the history*
Once the maximum size of the history has been reached and one more point is added, it should replace the "oldest" point, where "oldest" here means "not used in a long time" and not "added before a long time". Therefore, one has to separately keep track of point age (in addition to the order in which points where added to accomodate hint character assignment). Selecting a point from the history should move it to the top of the aforementioned list.

*visualization of points which are very close to each other*
It could happen that two points on the stack are very close to each other. In this case, hint characters can not simply be printed above the points. A simple and easy to implement solution would be to only add a point to the stack if it has a certain minimal distance (depending on `hint_size` and characters used per hint) to all other points already in the stack. A more sophisticated solution (possibly overkill) would be to move the character boxes away from their respective points and then have arrows point back to these points.

*persistent history set*
history should (optionally) be persistent across restarts, i.e. saved to a file on disk (including assigned hint characters and point age). Beneath a good format for that (how about yaml? There are parsers and serializers available for C), this also leads to the recently discussed question of where to save it (I would propose `XDG_STATE_HOME` with platform specific fallbacks).

### Hint mode for generic point sets

Once talking about a hint mode for the selection history, one may take this idea even further and think about a hint mode for a user specified set of coordinates (typically through a file and optionally including attributed characters). If and how to implement the user interface for this is of course subject to some debate, but when implementing the core hint mode functionality (also in connection with #100, the localized hint mode), such a possibility should be accounted for. Before commenting about implementation, here are some thoughts about a hint mode of the sort just described:

*Is this a job for warpd?*
First of all, the question arises whether this task should still be in the realm of warpd (or a combination of warpd-keyd if those two ever get fused). After all, clicking some predefined points in a fixed order would be a typical job for xdotool and friends. However, doing this when the order of clicking them is non-deterministic, or in other words _interactive_, should be a job for warpd. Example use cases are again those I [described](https://github.com/rvaiya/keyd/issues/158) when thinking about integrating warpd with keyd, in particular:

- playing chess (clicking 64 points of interest in a non-deterministic way)
- more generally: clicking points of interest in a specific gui application in non-deterministic order

In both cases, the history set would not have to be tediously built from scratch every time the application is used.

*Need for a helper script to generate hint set files?*
If this gets implemented, a helper script is needed to easily populate a file. Such a script would be started with hint characters as a command line option, then the user clicks on all points which should be included and these are added to the hint set file in order, including attributed characters (which might change during the selection process as the maximal number of points is not known beforehand). There should be an undo functionality to correct the last added point and also all points selected so far should be visualized on the screen. Later, such a script could be extended to also offer editing of an already built hint set file. For starters, a much simpler way would be to just edit a saved history stack by hand, if the file format is sufficiently easy to understand (it would be if yaml is chosen).

*configuration file syntax*
The configuration file syntax would have to be changed, as is already the case for #104 (multiple keys for the same action). I know that this would be a drastic measure, but in order to be future proof it might be a good idea to break backward compatibility here and pass to a more flexible format once and for all. For easy transition, warpd could throw an error upon detecting an invalid configuration file (for example one in old format) and print a message describing that the old format can be converted to the new one by running a provided script (which would be trivial to write, given the simplicity of the current format). Again, yaml is a good choice in my opinion as it is easily parsable and maintains readability. If you don't like it, how about introducing vim-like bind statements, so that one can for example write things like

```
bind M-f hint_mode_from_file("~/.config/warpd/hintsets/chess.hints")
``` 

or

```
bind M-f hint_mode_history()
```

*integration of warpd with keyd (again)*
As the hint characters assigned to points in a fixed hint set file are completely deterministic, this would allow for very powerful keyd macros of the type "click here and there, type something, then press enter and afterwards click somewhere again". The "click here and there" part would be as simple as repeatedly pressing the respective warpd activation key (which starts hint mode with the file in question) and then pressing the keys corresponding to the points one wants to click. 

### Future-proof implementation
No matter which of the above points get implemented, in order to future proof the code, I suggest to clearly separate tasks when implementing #100 (localized hint mode, which would now be a special case of the generalized hint mode just described) by:

1) introducing some 'point selection set' data structure consisting of a set of point coordinates, each marked with selection characters for that particular point
2) implement some standard routines to create such data structures (for example the grid needed for standard or localized hint mode)
3) implement the routine which draws this set on the screen in such a way that every point has its visual representation attached to it in some way (here I'm already thinking about the case of nearby points which have to be visualized in a non-standard way), so that it can easily be removed when narrowing down the selection (instead of just deleting columns/rows, now visualizations of all points of the set ruled out by the pressed user characters have to be removed from the screen). 
3) Make the controlling routine which takes a set, draws it on the screen, narrows down the selection to a single point and then executes some action generic by accepting as parameters:
- whether to stop after n steps or loop indefinitely until some exit key is pressed (to possibly accomodate future features like "select and click three points in a row"
- the action to take after each unique selection, i.e. just move the cursor, move and click left or move and click right (to possibly accomodate future features like "click after selection")

**Comment by rvaiya** [comment]
> How about a hint mode for the history stack?

I considered implementing something like this but didn't use hint mode enough in practice to invest the effort. This would probably increase its utility for those who do, so I am not opposed to it.

> hint character assignment Thinking about typical use cases, where one
> already has several interesting screen points in history

I suspect the annoying bit will be trying to remember whether or not you have the point of interest in your hint cache before deciding which mode to activate. There is also the problem of UI elements potentially moving with windows, but that affects history generally.

> Instead, it would suffice to complement the first four characters with a second one, once the actual stack size exceeds 26.

+1. It makes sense to use the minimum number of hints necessary, though I'm inclined to just limit the size of the stack to len(hint_chars) to begin with since this seems like a reasonable size.

> replacement of points in the history Once the maximum size of the
> history has been reached and one more point is added, it should
> replace the "oldest" point, where "oldest" here means "not used in a
> long time" and not "added before a long time".

+1 pruning least recently used hints makes sense.

> visualization of points which are very close to each other
> ...
> A simple and easy to implement solution would be to only add
> a point to the stack if it has a certain minimal distance

+1 deduping based on proximity seems like a natural solution.

> persistent history set history should (optionally) be persistent
> across restarts i.e. saved to a file on disk (including assigned

+1, this would also allow history to work with oneshot modes (and wayland by extension).  I originally intended to do this but never got around to it.

> hint characters and point age). Beneath a good format for that (how
> about yaml? There are parsers and serializers available for C), 

YAML seems like overkill, a simple custom format should be good enough.

> this also leads to the recently discussed question of where to save it (I
> would propose XDG_STATE_HOME with platform specific fallbacks).

+1. I was thinking about something like `~/.warpd_history`, but given that we are already using XDG paths for the config file, this probably makes more sense.

> a hint mode for a user specified set of coordinates
> [...]
> Is this a job for warpd?  
> [...]
> However, doing this when the order of clicking them is non-deterministic, or
> in other words interactive, should be a job for warpd.

I agree that this is a job for warpd, however I am unconvinced that the effort of defining a dedicated hint set for each application is worth the effort.  I can see the utility of full automation (xdotool style) as well as the value of interactive tools like warpd, but I don't see much practical use for a hybrid approach.

> more generally: clicking points of interest in a specific gui
> application in non-deterministic order In both cases, the history set
> would not have to be tediously built from scratch every time the
> application is used.

My instinct is that the number of keystrokes you save and the fact that any predefined hint set would require fixed window positions reduces the value proposition.

> playing chess (clicking 64 points of interest in a non-deterministic way

This is probably the most useful example, but even in this case the gains are marginal. Consider that two characters would be necessary to select a square (given that there are 64 of them) and that squares are already large enough to be covered by full screen hint selection. At this point the only thing you potentially save is the click keystroke and that can potentially be remedied by introducing an auto click mode using the current hint set.

A better solution would be to build this functionality into the client, which would allow you to leverage domain specific knowledge (e.g which pieces the user owns) facilitating uni-character selection.

> Need for a helper script to generate hint set files?  If this gets
> implemented, a helper script is needed to easily populate a file.

If implemented this would indeed make sense, though it would probably be a flag rather than a dedicated helper script.

> The configuration file syntax would have to be changed, as is already the case for #104 

It should be possible to extend the configuation syntax, though I haven't given it much thought.

> As the hint characters assigned to points in a fixed hint set file
> are completely deterministic, this would allow for very powerful keyd
> macros of the type "click here and there, type something, then press
> enter and afterwards click somewhere again". The "click here and
> there" part would be as simple as repeatedly pressing the respective
> warpd activation key (which starts hint mode with the file in
> question) and then pressing the keys corresponding to the points one
> wants to click.

I intend to add mouse support to keyd at some point which will probably also involve macro support. This should be enough to implement what you describe without warpd, though warpd might still be useful for discovering screen coordinates (possibly as part of a script)

> introducing some 'point selection set' data structure consisting of a
> set of point coordinates, each marked with selection characters for
> that particular point implement some standard routines to create such
> data structures (for example the grid needed for standard or
> localized hint mode)

You are describing the hint struct :P. The implementation should be fairly straight forward, though I remain unconvinced that the feature would be useful in practice.

**Comment by fboumol** [comment]
Let me just add the following shell function in case it helps. It uses `cnee` and it prints to stdout the next n (whatever it is number n) mouse clicks (using the three usual buttons). If you just use `logmouseclicks` (without any first argument) it acts like a daemon. Besides cnee it uses `xmousepos` to find the coordenates.

`logmouseclicks() { cnee --record --mouse 2>/dev/null | awk -v stop=${1--1}  'BEGIN { count=0 } /^7,4,0,0,[1-3],/ { count++; "xmousepos" | getline x; close("xmousepos") ; printf "%s\n", x ;} count==stop { exit}'; }`

If one prefers to use `xdotool getmouselocation` instead the following function does the same trick (but the output is slightly diferent):

`logmouseclicks() { cnee --record --mouse 2>/dev/null | awk -v stop=${1--1}  'BEGIN { count=0 } /^7,4,0,0,[1-3],/ { count++; "xdotool getmouselocation" | getline x; close("xdotool getmouselocation") ; printf "%s\n", x ;} count==stop { exit}'; }`

**Comment by rvaiya** [comment]
> Maybe a good idea would be to just offer a single custom hint mode, which takes the coordinates from a fixed file somewhere in the keyd config. 

I ended up implementing this in the form of a flag (`--query`) since it seemed like a reasonable compromise. With a bit of scripting and some WM bindings, it should be possible to achieve most things.

> If support for more
> modes are needed, one could either (re)start keyd with a different value for
> XDG_CONFIG_HOME, or make keyd load the hints from the external file on every
> invocation of the mode (inefficient, but not noticeable for the user), so that
> this could be managed through symlinks.

This seems quite cumbersome. I have long regretted not making warpd, 'warp' and forcing the user to launch it using window manager bindings in conjunction with flags (i.e what wayland users have to do anyway). 

The original justification for writing a daemon was to allow for caching of hint sets, which used to be quite expensive under the original X implementation (and still is to some degree with a large number of hints and a non-zero border radius).

> As the hint characters assigned to points in a fixed hint set file are
> completely deterministic, this would allow for very powerful keyd macros of the
> type "click here and there, type something, then press enter and afterwards
> click somewhere again". The "click here and there" part would be as simple as
> repeatedly pressing the respective warpd activation key (which starts hint mode
> with the file in question) and then pressing the keys corresponding to the
> points one wants to click.

I've always thought trying to ventriloquise GUIs like this is too fragile (since it relies on window
geometry among other things). If I find myself doing something frequently enough, I usually try and
automate it at the API level, but I realize this is not always possible/desirable.

> If you put everything on a special keyd layer and toggle it while playing, it
> would just require typing the coordinates of the two squares (so four
> keystrokes).

I assume you are baking the click into the macro, which I suppose is reasonable. I still think
chess is one of those instances in which a mouse really is the best tool. Even with 4 keystrokes, I
can't imagine being able to play faster than using my mouse.

> as you know I regularly have to use such dreaded software at work.

My condolences ;).

> Still, in at least half of the cases I need some fine tuning after selecting a hint, either through manual movement or the two step hint mode.

I also need *some* adjustment in about 50% of cases, but I usually find 1-2 taps of the directional keys sufficient.

> I tend to believe that quadrant selection is faster. If you agree, I'm happy to get my hands on this. It should not be that hard to implement.

For now I am going to start taking a more conservative approach to modes. There are already too many (soon warpd will be reading mail).

I am closing this for now, but if you experiment (should be easier with `--query`) and find something you think is objectively superior in real world use, feel free to lobby for it in another issue.

**Comment by rvaiya** [comment]
> Can't the performance penalty be solved by cache files (named in a unique way according to resolution and the value of hint_chars)?

The caching I am referring to is in connection with the X11 drawing logic which needs to live in memory.

> I tested this by creating a shell script which feeds hints (labelled by the board coordinates) to warpd via --query and clicks in a loop. Therefore, every move only requires typing two coordinates in a row. One of my chess playing colleagues (who can touch type and tell you the coordinates of every square on the board without thinking) served as a lab rat. He reported that he can play at least as fast as using the mouse and also mentioned the nice side effect that beginners can learn board coordinates while playing. Apparently, this way of indicating moves is also standard, see UCI. 

Interesting.

> He also said that a more efficient solution would be to allow for short algebraic chess notation, which typically reduces the number of keypresses to three.

I have an experimental chrome extension which facilitates two key selection on chess.com, though it forgoes algebraic notation to minimize the total number of strokes. 

After googling a bit I also found this:

https://chrome.google.com/webstore/detail/chesscom-keyboard/bghaancnengidpcefpkbbppinjmfnlhh?hl=en

which seems to support algebraic notation, though I haven't used it. 

I intend to polish my own solution and add lichess support when I have some spare time.

> While this is technically possible, it would of course be complete overkill and also reinventing the wheel, one could instead simply use dedicated chess software for this.

I think chess is one of those instances in which a dedicated solution makes sense, since knowledge of the pieces guarantees selection with a single key.

> Also, support for the standard notation for castling (O-O and O-O-O) and for promoting a pawn should be supported

I probably won't bother implementing standard notation since I think hints are more efficient and it has already been done.

All in all, this is a nice demonstration of the power of the --query option.

+1
