### ISSUE TITLE
Ideate some productivity enhancements

### ISSUE THREAD

**Issue by janmejay** [rvaiya/warpd#133]
@rvaiya thanks for this great productivity booster, this is exactly what I was looking for in so many ways. I have been using this the last few days and have some ideas that I want to pick your brain on (you have likely thought of all of them, perhaps most are in the roadmap already, but I don't know any better). Also, I feel pretty excited about the product and can perhaps help contribute support for xserver (not sure how soon or how much though, so best not counted upon), so if you are willing to accept some of these but don't have time to work on em, I can perhaps chip away at em slowly. If you in-principle like an idea I can file a dedicated issue for it after we close this one. Here is the list, wdyt about:

* A variant of hint-mode that powers content based navigation? Eg. variants such as:
  * detect text using some OCR and place hints above
  * detect color change and use avg-color of a portion of screen-space (say a configurable portion of 40x30px can be used to compute avg-color and place hints in the middle of every such rectangle with change of avg > a configurable threshold)?

* Passthru of keyboard events that warpd doesn't have a hander for? Eg. Alt+tab or Meta+1 etc can be passed on to the window-manager if warpd doesn't have a handler for em.
  * A possible variant: Allow user to specify key-sequences to be passed-thru (or even allow specifying mapping of key-seq to be passed thru), Eg. `g` => `Ctrl+g` implies user wants Ctrl+g to be passed everytime they press `g` in warpd-modal.

* Ability to write callable handlers for some shortcuts (or seq of actions). Eg have a first-class concept of rectangle-marking (similar to drag followed by copy and exit), let us call it rectangle marking that one can write a handler to, use a shortcut similar to copy that triggers user-script? capturing screenshots is one usecase that can be powered using this. I haven't really thought of modality of doing this, I imagine there is an array of trade-offs to be considered for instance between allowing user to provide a share-lib vs. fork-exec of a path vs. lua-script that runs in warpd etc. 

* Customizable density of hint points. Many variants are possible
  * Allow user to specify a probablity map (say in a nested r-tree style json file that maps node to density). Eg. 1 guarantees a hint, 0 guarantees no hint and warpd uses exponential / linear distribution to place hints for the rest, which is scaled by the density-coefficient specified.
  * One can build on the above by generating such a r-tree density-coeff map based on usage (users would typically tend to use some hints more than others) and when not overridden this can be used to power custom-grid (a different key-sequence than default hint-mode).
  
* Shortcuts for page-up / page down (this can perhaps be achieved by the pass-thru feature)

I'll probably come up with more itches to scratch immediately after I post this. It'll be great (if its ok with you) if this can be kept open for a few days.

**Comment by janmejay** [comment]
BTW, I do not have any experience with xserver protocol / xlib, so I do not know if what I say makes any sense or is possible / easy / difficult to do.

**Comment by janmejay** [comment]
True to my promise, I did recall another thing I wanted to add here:

* Ability to use modifier keys while clicking (eg. Ctrl+click or Shift+click etc) such that modifier is passed as part of the click event.

**Comment by rvaiya** [comment]
> A variant of hint-mode that powers content based navigation?
> [...]

I originally considered implementing content aware hints but didn't think it was feasible to do the requisite analysis on the fly. I am probably wrong about this, but even if it was possible it would require multi platform support for obtaining screen content which may not be possible (wayland in particular might pose an issue).  If you have a better idea about how something like this might be implemented in practice feel free to create a dedicated issue.

Having said that, I would encourage you to experiment with hint density/size before pursuing this idea. It is surprisingly easy to pinpoint most areas of the screen with the right settings and a bit of practice. I almost never need more than 3 key strokes (usually 2) to select a given UI element. There is also a two-step hint mode on the horizon (#100), but I personally don't think it will greatly improve efficiency.

> OCR

I'm not familiar with the state of OCR, but my understanding is that this would involve pulling in some fairly large training data and would pose the same challenges as content based navigation.

> Passthru of keyboard events that warpd doesn't have a hander for? Eg. Alt+tab or Meta+1 etc can be

Implementing this in a cross platform way is non-trivial. I may ultimately end up reimplementing parts of warpd in keyd, which should make this possible out of the box, but that will take some time.

> Ability to write callable handlers for some shortcuts (or seq of actions). Eg have a first-class concept of rectangle-marking (similar to drag followed by copy and exit), 
> let us call it rectangle marking that one can write a handler
> to, use a shortcut similar to copy that triggers user-script?

This is beyond the scope of warpd. There are already other tools that do this (e.g scrot, slop?).

> Customizable density of hint points. Many variants are possible

This is already possible by tuning `hint_chars`.

> Allow user to specify a probablity map (say in a nested r-tree style json file
> [...]

I'm not sure why the user would ever want to specify this by hand. Full screen hint selection will almost always be superior once the number and size of hints have been properly tuned. Having said that, hints based on history make sense and are planned for a future release.

> Ability to use modifier keys while clicking (eg. Ctrl+click or Shift+click etc) such that modifier is passed as part of the click event.

This should work in the latest commit (it recently broke because of some changes to the input logic).

**Comment by janmejay** [comment]
I wanted to use `q` for exit (for `esc` key feels too far from center of the keyboard), so that made density worse for me. I added `;` and `,` for additional hint-chars, but there is still a remarkable amount of speed-up when one uses browser extensions such as `Vimium`. That approach doesn't always work but when it does I think its pretty awesome.
Having all features on all platforms would be great, but I guess gracefully degrading on some platforms isn't really too bad so if this can be made to work for xserver, I guess that would be a win too. 
Looks like you see value in this, I'll try to play with this whenever I find some time and report back what I learn. I suppose xserver knows coordinates where fonts are drawn, getting it out in some way (not sure if there is a way to do this) would work. Another idea I can play with is color and try to pick up areas where avg-color changes significantly.

Not filing an issue for now, will create one if I see some success.

About the screenshot thing, capturing screenshots was just an example. I want a way to do it without having to activate the touchpad for it. I can't really do it using warpd at this point because tools such as xfce4-screenshooter (which I use) and others such as slop grab input and warpd normal-mode can't be activated at that point. If we had a way of first selecting a rectangle using warpd then invoking screenshot program as a subprocess with coordinates to the rectangle would do the trick. Am I making sense? Or may be I have something misconfigured and xfce4-screenshooter area mode can be used with warpd (if this is the case can you please point me in the right direction)?

About the probablity-map and history based hints is kind of trying to drive towards content based navigation. These will be very useful in some environments (such as with tiling window managers like `i3` or `xmonad`). I meant probablity-map based on r-tree can be the implementation vehicle that history-based-hints feature can use. If exposed it can be valuable on its own (atleast to twm users) even before history-based-hints is ready.

I'll try to build off master for the Ctrl+click thing.

**Comment by janmejay** [comment]
Another idea: default hints are built using lower-case characters. What do you think about a config (bool) that retains all of existing behavior but renders the hints in upper-case? So one can access hint `ac` using key seq `a` and then `c`, but it presents itself on the screen as `AC`?

I brought this up because lower-case letters such as `l` and `i` can sometimes be a bit hard to distinguish in a split-second but one can easily tell `L' and 'I' apart. 

Would you be ok with this being exposed as a config (off by default, retaining current default behavior)?

**Comment by janmejay** [comment]
2 more independent things:

What do you think about another set of shortcuts for moving cursor in quantas per keystroke. Eg. `j` moves it forward continiously but say `Ctrl+j` or say `u` moves it by 100px per stroke. 100px is configurable.

Is there a way to scroll horizontally?

**Comment by rvaiya** [comment]
> I wanted to use q for exit (for esc key feels too far from center of the
keyboard), so that made density worse for me. I added ; and , for additional
hint-chars, but there is still a remarkable amount of speed-up when one uses
browser extensions such as Vimium.

You probably need to adjust your hint size. I expected this to be the case, but I find warpd faster (as a former vimium user). See #100 for a demo. Having fixed position hints allows the user to memorize hint position and potentially reduces both cognitive and processing overhead (e.g no need to wait for the DOM to load).

> Having all features on all platforms would be great, but I guess gracefully degrading on some platforms isn't really too bad.

Full platform support would be necessary. X is on the deprecation path.

> I'll try to play with this whenever I find some time and report back what I learn.

+1

> I suppose xserver knows coordinates where fonts are drawn getting it out in some way (not sure if there is a way to do this) would work.

If you are proposing using this as a substitute for OCR, this probably won't work. Most toolkits do their own font rendering and bypass the X server entirely.

> Another idea I can play with is color and try to pick up areas where avg-color changes significantly.

Feel free to experiment with this, but my instinct is that this probably won't be enough to cleanly identify UI elements. Things like text and button placement will produce too many false positives without some kind of sophisticated CV algorithm to weed them out. If it is possible, it will likely require a hammer like ML and large amounts of training data.

> Not filing an issue for now, will create one if I see some success.

+1

> If we had a way of first selecting a rectangle using warpd then invoking screenshot program as a subprocess with coordinates to the rectangle would do the trick.

I might consider adding a button which prints the current screen coorindates. This would making a wrapper script to do what you describe trivial.

> About the probablity-map and history based hints is kind of trying to drive towards content based navigation.

If this works well enough it makes sense to integrate it directly rather than have some external program generate and feed the hints to warpd.

> I meant probablity-map based on r-tree can be the implementation vehicle that
> history-based-hints feature can use. If exposed it can be valuable on its own
> (atleast to twm users) even before history-based-hints is ready.

Users will still need a way to generate the hint file, in which case it makes sense to just use warpd's built in functionality

Before I would consider inclusion of such a feature it would have to meet the following criteria:

 - Be demonstrably more efficient than full screen hints
 - Reliably detect UI elements
 - Support all platforms
 - Avoid pulling in too many/large external dependencies

If you can produce a working proof of concept that does the requisite image analysis I can help with the platform support (though this may ultimately be a bottleneck).

> Picked up latest master, it works, but it doesn't seem to respect xmodmap overrides. 

This is a known bug. You will need to use an evdev based remapping tool like keyd.

> What do you think about another set of shortcuts for moving cursor in quantas per keystroke. Eg. j moves it forward continiously but say Ctrl+j or say u moves it by 100px per stroke. 100px is configurable.

You can achieve this with the accelerator key.

> Is there a way to scroll horizontally?

No. I might release a patch for this soon.

**Comment by janmejay** [comment]
For the OCR thing, I plan to play with _tesseract ocr_ and try to get coordinates and text. 

I bumped up size, it does appear to work better, also replaced some hint-chars with less ambiguous looking ones. I think once I get keyd to work with warpd I can bring `q` back into the hint-char-set and use `Ctrl` down+up for `Esc`, that'll be really good.

I can't really use accelerator key because I use emacs like bindings (so C-n for down and C-p for up etc), it'll likely be more difficult to hold another key down while using a key-combination such as this one. I can imagine it working quite well for single-key based nav (which is the default), but my muscle memory works better with emacs-style bindings. I guess there will be others that'll want this a bigger-jump alternative too.

A couple more ideas, wdyt about
* Bookmarking (based on position for now, but eventually, if OCR thing works well, based on content too)?

* You mentioned it may be difficult to implement keyboard-events that do not have any matcher back to the environment. I suppose you must have considered picking events up from `keyd` directly and never grabbing keyboard in normal / hint mode? In such a `keyd` can act as a splitter or filter (the key-sequence may either be consume by a handler, it happens to be a `warpd` handler in this case, or be passed thru to uinput). I was wondering why this wouldn't work well. I understand you may not want to tie `keyd` and `warpd` together and when there is no `keyd` this isn't really something that can be done, but I guess this is another case of graceful degradation (the passthru mode is made available only in combination with `keyd`?). I think the fact that mouse / touchpad is active all the time lowers cognitive overhead of enabling / disabling it which is powerful, having to activate and exit normal / hints mode makes it somewhat less smooth than it can be (increases the keystrokes required to accomplish something, creating some drag), eg if one needs to type something short before clicking a button, keeping normal-mode active can be powerful.

**Comment by rvaiya** [comment]
> I bumped up size, it does appear to work better, also replaced some hint-chars
> with less ambiguous looking ones. I think once I get keyd to work with warpd I
> can bring q back into the hint-char-set and use Ctrl down+up for Esc, that'll
> be really good.

+1

> I can't really use accelerator key because I use emacs like bindings (so C-n
> for down and C-p for up etc), it'll likely be more difficult to hold another
> key down while using a key-combination such as this one. I can imagine it
> working quite well for single-key based nav (which is the default), but my
> muscle memory works better with emacs-style bindings. I guess there will be
> others that'll want this a bigger-jump alternative too.

+1. It is better to avoid fighting the modal nature of warpd and embrace the bindings.  It is ultimately more efficient.

> Bookmarking (based on position for now, but eventually, if OCR thing works well, based on content too)?

An older version of warpd has something akin to vi marks, but the end result didn't result in any real efficiency gains and just added more bloat.

> I suppose you must have considered picking events up from keyd directly and never grabbing keyboard in normal / hint mode?

Yes, a potential merge has been discussed at length in both keyd and warpd issues. It may or may not eventually happen. There are some good technical arguments to be made on both sides.

> I was wondering why this wouldn't work well.

It would require (at least); root, time, energy, a macos port, and introduce a number of other subtle problems.

> I think the fact that mouse / touchpad is active all
> the time lowers cognitive overhead of enabling / disabling it which is
> powerful

> having to activate and exit normal / hints mode makes it somewhat
> less smooth than it can be (increases the keystrokes required to accomplish
> something, creating some drag), eg if one needs to type something short before
> clicking a button, keeping normal-mode active can be powerful.

It is not the panacea it seems, but it would make some implementation details easier. A lot of work went into experimenting with various platform specific APIs to get them to behave properly (especially X) to make the end result seamless. Doing this properly is non-trivial and I still have mixed feelings about it.

**Comment by rvaiya** [comment]
I'm closing this for now, but feel free to create another issue if you end up with a usable mvp.
