### ISSUE TITLE
little mem leak in /x/screen.c

### ISSUE THREAD

**Issue by kyx0r** [rvaiya/warpd#156]
Hi, I'm pretty sure you can call Xfree(xscreens); after the loop here:
https://github.com/rvaiya/warpd/blob/master/src/platform/X/screen.c#L26

You aren't using xscreens anymore.
Refer:
The XineramaQueryScreens() function returns info about each individual output device within the Xinerama Screen. The integer pointed to by the number argument is updated to the number of output devices listed in the returned array of XineramaScreenInfo structures. XineramaQueryScreens() returns NULL and sets number to 0 if Xinerama is not active.

The pointer returned should be released with [xfree](https://linux.die.net/man/3/xfree)(3) when no longer needed.

BTW, any plans to make it work on suckless x11 server like tinyx, currently it doesn't work since you are heavily reliant on xinerama and xkb xorg drivers.

**Comment by kyx0r** [comment]
@rvaiya PING

**Comment by rvaiya** [comment]
Sorry, I forgot to respond to this. Yes, you are correct about the Xfree call, though in this case it probably doesn't matter since init_screens is only called once. I've pushed a patch for it but I wasn't scrupulous in some of the initialization logic, so I wouldn't be surprised if there are similar deficiencies littered throughout (though I don't believe there are any major leaks). 

> BTW, any plans to make it work on suckless x11 server like tinyx,

Not at the moment. I'm a fan of the suckless design philosophy, but a suckless X implementation sounds like an oxymoron :P. Stripping the xinerama and xinput dependencies would be non-trivial. Wayland is bad enough, I'm not keen on maintaining two different X implementations. Stripping xinput would also cause functional regressions, since it is presently used to circumvent limitations in native X grabs (which is an ugly hack). Having said that, patches are welcome if you want to invest the effort.

**Comment by kyx0r** [comment]
Alright. Thanks.
