### ISSUE TITLE
Feature Request : AZERTY Support

### ISSUE THREAD

**Issue by Babilinx** [rvaiya/warpd#163]
Hi! I'm using an `azerty` keyboard, and the implementation of your project is not that good on this keyboards.

I wanna make a pull request with the support of `azerty`, but I have one question :
 - Did you only define inputs in `/scr/platform/{X, macos, wayland}/input.{h, c}` and in `src/input.c` ?
   (To be sure that I don't miss anything)

Thanks for your work !

**Comment by rvaiya** [comment]
Thanks for your interest. Doing this properly will also likely require tweaks to the platform code which consists of a collection of hacks and is largely keycode (rather than keysym) oriented. This will require some familiarity with the different platform specific APIs. I might invest some time in this later, but current efforts are directed to porting warpd functionality into [keyd](https://github.com/rvaiya/keyd).

**Comment by rvaiya** [comment]
As of f3450c74d this should work out of the box.
