### ISSUE TITLE
Feature Request: Keep history of clicks in discrete mode as hints for hints mode

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#20]
Hi.. It is me again.... Sorry but I just love annoying you :P

Sorry for annoying you so much but you have to agree this one is at least to keep in mind. Most boring software with lots of point and click are usually receiving clicks in the same screen positions. What if we could keep track of the last clicked positions, I mean the number of positions to save could be configurable or so, and then we display a different hint over the other hints for those positions. I mean the last clicked position if the user used discrete mode, meaning the default hints did not work. I really think this is a way to improve the usage of this a lot!

Another thing would be maybe have in discrete mode the vim "m" command... I mean bookmark a position during runtime, so you can define the hints like single letter hints or whatever, for those bookmarks (maybe q like recording a macro in vim but who cares by the defaults anyway). Also in the future could there be a menu or a gui to load profiles of those bookmarked positions at runtime...... But yeah I am daydreaming a bit far from what we have now. But I think this is a cool direction this could evolve to.

**Comment by rvaiya** [comment]
> Sorry for annoying you so much but you have to agree this one is at least to
keep in mind. Most boring software with lots of point and click are usually receiving clicks in the same screen positions. What if we could keep track of the last clicked positions, I mean the number of positions to save could be configurable or so, and then we display a different hint over the other hints for those positions.

I'm not sure how this would work. What would happen if a historical hint overlaps with a normal one? In general I don't really see the value of something like this given that almost any location on the screen can be hit in under 4 key strokes. 

> I really think this is a way to improve the usage of this a lot!

I think you might just need to increase the size of your character set. I have no problem hitting most buttons on the screen in fewer than 3 keystrokes.

Observe

![](http://0x0.st/iJSD.gif)

> Another thing would be maybe have in discrete mode the vim "m" command... I
mean bookmark a position during runtime, so you can define the hints like single letter hints or whatever.

My opposition to this idea is similar to the one above. It also breaks when window placement changes. Using hints as they presently exist is sufficiently fast and less fragile than dynamically assigning shortcuts at run time. If you find yourself needing to click a specific button so frequently that saving a single keystroke is meaningful then you might want to consider using a more keyboard friendly piece of software.

> Also in the future could there be a menu or a GUI to load profiles of those bookmarked positions at runtime.

A GUI seems like overkill. I am a strong believer in Zawinski's Law :P.

**Comment by matheusfillipe** [comment]
> I'm not sure how this would work. What would happen if a historical hint overlaps with a normal one? In general I don't really see the value of something like this given that almost any location on the screen can be hit in under 4 key strokes.

 You aren't lazy enough then :P.  But 2 key strokes would be better than 4. Maybe a new as mode which is history mode with the last discrete mode clicks as hints then, this way there won't be overlapping?  I think that is a better idea.

> I think you might just need to increase the size of your character set. I have no problem hitting most buttons on the screen in fewer than 3 keystrokes.

That is true, my hints are big, but like it this way :P But consider this because again, 2 keystrokes are better than 3 anyway xD. And like in my case it is a high dpi screen and I use some scaling but it still some applications have things that are really hard to hit. Anyway I like  to keep the hints bigger because then I can see what i have to type without any effort.

> Observe
> 
> ![](https://camo.githubusercontent.com/8d3d30baf1be30ab9e3e1871a76ef83bb84a94d0/687474703a2f2f3078302e73742f694a53442e676966)

I could never use that small and so many hints :sweat_smile:  I actually need glasses you could say but that's not the point here! :P

> My opposition to this idea is similar to the one above. It also breaks when window placement changes. Using hints as they presently exist is sufficiently fast and less fragile than dynamically assigning shortcuts at run time. If you find yourself needing to click a specific button so frequently that saving a single keystroke is meaningful then you might want to consider using a more keyboard friendly piece of software.

Hmm I can see what you mean. I am usually use most of my applications maximized and on tilling window managers that would really not make much sense unless you have static environments and layouts (which I actually do have). But yeah, for the general user that moves windows around that would make no sense.

Anyway, maybe you could consider something like `S-m + a` on discrete mode to save the position you are on as "a", just in runtime, like a marker in vim, then when you enter in discrete mode again and hit `' a` (like to go to the marker a in vim's defaults) you get where you saved. This is like defining your custom hints at some positions, you could use any keystroke and then when on discrete mode you get on those positions instantly. What do you say?

**Comment by rvaiya** [comment]
> You aren't lazy enough then :P.  But 2 key strokes would be better than 4.  Maybe a new as mode which is history mode with the last discrete mode clicks as hints then, this way there won't be overlapping?  I think that is a better idea.

Given the size of most UI elements most buttons should be reachable with 2 keystrokes. You usually only require more if you are trying to do something precise (like text selection) which usually requires a degree of flexibility that would not be improved by a history mode.

> That is true, my hints are big, but like it this way :P But consider this because again, 2 keystrokes are better than 3 anyway xD. And like in my case it is a high dpi screen and I use some scaling but it still some applications have things that are really hard to hit. Anyway I like  to keep the hints bigger because then I can see what i have to type without any effort.

You can still accommodate quite a few hints on the screen with a larger hint size. There is a lot of wasted space. Have you tried playing with `hint_characters`?

> I could never use that small and so many hints :sweat_smile:  I actually need glasses you could say but that's not the point here! :P

The demo makes it seem worse than it really is. That was taken on a 24" 4K screen and scaled down into a 1080p image. It is quite readable at that resolution (certainly no harder to see than the text on most websites). There is also plenty of room to increase the font size without changing the number of hints.

> Anyway, maybe you could consider something like `S-m + a` on discrete mode to save the position you are on as "a", just in runtime, like a marker in vim, then when you enter in discrete mode again and hit `' a` (like to go to the marker a in vim's defaults) you get where you saved. This is like defining your custom hints at some positions, you could use any keystroke and then when on discrete mode you get on those positions instantly. What do you say?

I'm not sure how this differs from a dedicated history mode. The implementation you describe requires three keystrokes (an activation key, a single quote and a mark) and only accommodates 26 locations. The current implementation requires the same number of strokes and enables the selection of nearly 1000 screen locations.

Most of your suggestions seem to be vi centric. `warpd` is not intended to emulate vi. The vi-like default bindings are just a convenience but the program has fundamentally different use patterns because it is movement rather than text oriented.  You need to think about mouse movement in a different way than you think about text manipulation. Certain tasks are faster with `warpd` (with practice) while others will always be faster with a mouse. The program is really designed to supplement a keyboard driven setup than supplant a mouse driven one. If you need to perform a specific action a lot most software will have a keyboard shortcut (or else can be replaced by one that does).

**Comment by matheusfillipe** [comment]
Well my screen is 15" because it is a laptop. My point is just that 2 strokes is better than 3. Could be a history mode or something inside the discrete mode. 

> If you need to perform a specific action a lot most software will have a keyboard shortcut (or else can be replaced by one that does).

This program is serving to me exactly as a way to have shortcuts that some programs don't have or that I couldn't find. Like a universal shortcut creator tool or whatever. All I mean is to have a way to save a position from discrete mode so it is just a few keystrokes away. 

I agree that you can set up in the hints size in a way that everything is just 3 keystrokes away but that will still requiring some thinking every time. What I want is to be able either save manually or have a history a position of discrete mode and be able to instantly return to it and go out something else.

**Comment by rvaiya** [comment]
> Well my screen is 15" because it is a laptop. My point is just that 2 strokes is better than 3. Could be a history mode or something inside the discrete mode. 

The same applies to my 1440p 14" laptop. Screen size is generally irrelevant since UI elements are scaled accordingly. Your hint size should be chosen in proportion to the average UI element on your screen.

> This program is serving to me exactly as a way to have shortcuts that some programs don't have or that I couldn't find. Like a universal shortcut creator tool or whatever. All I mean is to have a way to save a position from discrete mode so it is just a few keystrokes away. 

That isn't what `warpd` is designed for. If you really want a way to script specific GUI actions you probably want to use something like `xbindkeys` in conjunction with `xdotool`. I wouldn't recommend doing this as there are almost always better ways of achieving what you want using the keyboard.

> I agree that you can set up in the hints size in a way that everything is just 3 keystrokes away but that will still requiring some thinking every time. What I want is to be able either save manually or have a history a position of discrete mode and be able to instantly return to it and go out something else. 

This seems like false economy to me. The cognitive overhead of storing and memorizing hints at run time with a dedicated key yields a less flexible solution that may or may not end up saving a single keystroke. With a large enough number of hints the current mechanism is more flexible and equally (if not more) powerful with a bit of practice. I find moving my eye to the target and then activating hint mode before selecting a hint requires almost no effort. I submit that the vi-like mark mode you suggest is no more intuitive for the average user. It just happens to be a paradigm you are familiar with.  There is always a trade off between the time you spend learning to use your tools and the versatility they provide you. Personally I adjusted to `warpd` quite fast and found hint more more flexible than I originally anticipated.  Adjusting `hint_characters`, `hint_width` and `hint_size` is the key to successful usage. It may also help to map the activation key to a dedicated key on your keyboard (I do this).

I may consider adding a dynamic jump list (C-o, C-i in vim) at some point, but this is not high on my list of priorities.

**Comment by rvaiya** [comment]
I'm closing this for now. If you feel strongly about it and feel you can make a persuasive case for a similar feature feel free to open another issue.
