### ISSUE TITLE
Could not create virtual pointer on KDE Plasma 5.27.2

### ISSUE THREAD

**Issue by Calebe94** [rvaiya/warpd#234]
Every time I run the command `warpd --hint` the following error is shown:

```
Could not create virtual pointer (virtual pointer unsupported?)
```

How can I solve this issue?

System Info:

```
OS: Debian 12 (Bookworm - testing)
Kernel: 6.1.0-7-amd64 (64-bit)
DE: KDE 5.27.2 (Wayland)
```

**Comment by rvaiya** [comment]
Unfortunately KDE is unsupported since it doesn't implemented the requisite protocols. The wayland situation is a bit of a mess right now. You might want to keep an eye on [keyd](https://github.com/rvaiya/keyd), which will eventually add support for something like warpd's hint mode using lower level input primitives. Alternatively you can use X, which should work as is.

**Comment by Calebe94** [comment]
I was using `warpd` on XFCE and it was working great. I was afraid that the error was because KDE uses Wayland.
Thanks for your response and I'll keep and eye on `keyd`.
