### ISSUE TITLE
[Question] Transparency in picom

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#30]
How should I go about making the transparency works on a tilling window manager
or milimalistic DE that uses picom as its compositor? Should it work by
default? Well in my case it isn't (it was working on KDE).

I tried adding picom rules for wm_class = warpd and warp but they didn't work,
as far as I understand this is just drawing fancy shaped windows (using this
for one year and i have no idea lol). So it should have a window class right?
Or title? Or name? How can I make this work.

**Comment by matheusfillipe** [comment]
I figured it out. It has the wm_class warp, I was confused because of a blur rule I had on my picom.

**Comment by rvaiya** [comment]
Sorry for the prolonged response. It has been some time since I touched the code but I believe adding a compositor to the equation complicates things a bit. Right now I ignore redraw requests which would probably need to be implemented in order to properly interface with such things. It shouldn't be too much work but given that you seem to have got it working and (as far as I know) we are the only two people who actually use the program I am not inclined to invest the time. Let me know if you encounter any issues.

**Comment by matheusfillipe** [comment]
Oh its been working nice. The only little problem that bothered me so far is that the cursor disappears after clicking but this only happens on TelegramDesktop which is weird. (I mean the normal mode cursor):

![Peek 2021-06-06 22-29](https://user-images.githubusercontent.com/24435787/120948005-8be2bd80-c717-11eb-8d11-e7e9cff3c98b.gif)

**Comment by rvaiya** [comment]
I see. It seems like it may be related to the same potential redrawing
issue. If I have some time later I will look at it though it isn't a
priority right now. If this really bugs you let me know and I will take a
closer look at it.
