### ISSUE TITLE
How to change shortchut?

### ISSUE THREAD

**Issue by bommbo** [rvaiya/warpd#34]

**Comment by bommbo** [comment]
Alt and Meta is same key,So I want to know to change shortcut? I used gnome-tweak to change the keys. But I still hope to use other shortcut.

**Comment by rvaiya** [comment]
Meta corresponds to the super key (mod4) unless you have remapped it. Thus M-A-x corresponds to alt + windows key + x. If you just want `windows key+x` you can do `M-x`. If this doesn't work it is probably because you have either changed your mod map or because the key combination is already bound in your window manager.  There is a bug which currently causes warpd to fail silently if it can't grab the key, you can force it to produce an error message by running it in the foreground (e.g `warpd -f`).

**Comment by bommbo** [comment]
Maybe wayland problem. xorg is find.

**Comment by rvaiya** [comment]
Wayland uses a completely different input stack. I believe it has backward compatibility for some XGrab* calls but warpd abuses some of the hairier corners of xinput to achieve its objective. Wayland is unsupported and I would be surprised if it worked at all.

**Comment by bommbo** [comment]
But I found another problem.When I use warpd. all window manager shotcut is slow.

**Comment by rvaiya** [comment]
Can you elaborate? I assume you are referring to X (wayland is unsupported). What is your DE/WM, which shortcuts are slow? Are you running any other input related programs?

**Comment by bommbo** [comment]
OS: Manjaro Linux x86_64
DE: GNOME 40.4 xorg
window manager: pop shell
The shotcuts about "Swifch focus to window down/left/right/up" is slow. I set alt+ h/j/k/l to swiftch focus to window. maybe I use "alt“ key?

**Comment by rvaiya** [comment]
My guess would be colliding key bindings. A-h/j/k/l are the default warpd scroll keys, you will probably want to remap them to avoid conflicts.

**Comment by rvaiya** [comment]
Did you ever solve this? I've changed the default scroll keys and added some additional checks in the latest commit, but updating your config file should also have fixed the problem.

**Comment by bommbo** [comment]
Thankyou!!! I have fiexd this problem.
