### ISSUE TITLE
pointer goes outside the screen

### ISSUE THREAD

**Issue by Ultrahalf** [rvaiya/warpd#35]
![image](https://user-images.githubusercontent.com/41832211/133883558-f6189808-44cd-427c-9d0b-be6892e6d4fa.png)
top side and left seems to work fine, but when I try $(S-4) it goes outside the screen same with bottom, on a single monitor

great project btw
for some reason I think triangle would better than circle(because Idk if this is a me problem but when try to point at something only  the top left part of the circle shows some action(click), it makes sense normal mouse pointer is slightly tilted to same direction) is there a way to change the cursor

**Comment by rvaiya** [comment]
Sorry for the prolonged response. What you describe is expected behaviour since, as you observe, the actual pointer is at the top left of the visual indicator. Thus S-4 positions the pointer at the very edge of the screen causing the visual indicator to be off screen (but the pointer is still on the right most pixel). 

The visual indicator is just a normal window and should actually be a square, but I'm assuming you have some kind of compositor running which rounds off window edges making it appear like a circle (since it is basically a tiny window). You should be able to define a rule somewhere in your compositor to ignore the warp window and recover the well defined edges. Personally I just keep my indicator as small as the active part of the pointer so I don't have this problem. 

On a separate note, the actual cursor should be completely hidden but it seems that some DEs/Window Managers ignore the x fixes extension (it works on my machine). I'm not sure if it is possible to fix this but if it bothers you I can allocate some time later.

**Comment by Ultrahalf** [comment]
I tried lowering the size of cursor seems to do the job. Ah i forgot about the compositor
the actual cursor only comes in the scrot.

>  What you describe is expected behaviour since, as you observe, the actual pointer is at the top left of the visual indicator. Thus S-4 positions the pointer at the very edge of the screen causing the visual indicator to be off screen (but the pointer is still on the right most pixel).

i see thanks for the detail
