### ISSUE TITLE
Feature reuqest: cross platform

### ISSUE THREAD

**Issue by fire3420** [rvaiya/warpd#37]
Is it possitble to make this project to cross-platform?

I really love this project, so I'm thinking about making this project as an cross-platform using python.

Since this project has really adorable features, and some of them could be hard to implement in cross platform, I think starting with implementing hinting could be helpful

Do you have any thought about that?

**Comment by rvaiya** [comment]
> I really love this project, so I'm thinking about making this project as an cross-platform using python.

Thanks for your interest, I am glad someone else is getting use out of it :).

> Since this project has really adorable features, and some of them could be hard to implement in cross platform, I think starting with implementing hinting could be helpful

As far as I know, there isn't really a good cross platform way to achieve this. Most cross platform toolkits like GTK don't allow you to paint over the entire screen or grab control of the keyboard since they are designed for writing normal applications. Wayland, for instance, regards giving a client control over the keyboard as a security risk. 

I'm not sure about OSX or Windows but, assuming it is possible, it would almost certainly involve platform specific logic.  Even getting warpd to a usable state with X required abusing xinput and the end result still doesn't play nicely with some input related apps (e.g synergy).

**Comment by wearpants** [comment]
I'm starting to play around with iOS/OSX for the advanced accessibility features, and am really missing `warpd` (it's the major thing keeping me on Linux at this point TBH). Would seriously consider paying somebody to build this for Apple.

Some related projects I found below; none of them have hint mode or  the level of sophistication as warpd, bu maybe a place to start:


- [keynav for Linux, very similar to warpd grid mode](https://github.com/jordansissel/keynav)
- [OSX port of keynav](https://github.com/h2ero/XEasyMotion)
- [grid mode for OSX](https://github.com/trishume/QuickMouse)
- [navigate by GUI element name](https://shortcatapp.com/)
- [cliclick OSX mouse scripting](https://github.com/BlueM/cliclick)
- [more OS X input customizing, incl. mouse keys](https://karabiner-elements.pqrs.org/)

**Comment by rvaiya** [comment]
I am unfamiliar with OSX but a cursory look at XEasyMotion suggests it is using a deprecated API (Carbon). A port (or rewrite) might still be possible if the necessary APIs exist or the old ones still work on the latest macOS and might be an interesting exercise. Unfortunately I don't have a macbook.

**Comment by wearpants** [comment]
Yeah the Carbon APIs were killed off several years ago it seems - I will ask a friend about its viability under Cocoa

**Comment by rvaiya** [comment]
The latest release adds macos support.

**Comment by fire3420** [comment]
Awesome! Let me try it

**Comment by rvaiya** [comment]
Let me know how it goes :). I am closing this for now.

**Comment by mercifulboss** [comment]
> Wayland, for instance, regards giving a client control over the keyboard as a security risk.

It can be done. See the text expander “espanso”, it works via Wayland by putting itself as a system service. I think a similar thing can be done here
