### ISSUE TITLE
Feature Request: run it once (instead of daemon mode) with a geometry command line option?

### ISSUE THREAD

**Issue by fboumol** [rvaiya/warpd#40]
Thanks for this software. I find it really useful.

Could it be possible to use it as a regular command instead of a daemon mode? This would provide an easy method to provide xinerama support (see below).

There are a lot of keybinding "daemons" (xbindkeys, the ones given by window managers, etc) out there, and so I would prefer to use warpd in the already running daemon, instead of running a specific one for warpd. I see this as a particular case of the well known unix philosophy.

Moreover, it would be great if the command line accepts an option to select the mode (hints, normal, etc) and a command line option to specify the geometry rectangle (in your current code you assume that this rectangle is the full screen). As far as I know there is a standard way to refer to the geometry rectangle: "860x540+20+0" refers to the rectangle with width 860 and height 540 and with left-upper corner at (20,0), etc

Being able to specify the geometry rectangle would solve the xinerama issue in an obvious way, because we could use the keybinding daemon to use different commands to launch warpd depending on which screen we are currently focused.

**Comment by rvaiya** [comment]
Thanks for this software. I find it really useful.

> Could it be possible to use it as a regular command instead of a daemon mode? This would provide an easy method to provide xinerama support.

The early prototypes used to have such a 'oneshot' mode but they were replaced in favour of a dedicated daemon for a few reasons. The main one is that some of the drawing operations are expensive (especially hint mode) so running as a dedicated daemon allows warpd to cache some of them and and make it performant. It would be theoretically possible to retain some of these benfits by forking and adding some kind of IPC mechanism but this would add unecessary complexity.

> There are a lot of keybinding "daemons" (xbindkeys, the ones given by window managers, etc) out there, and so I would prefer to use warpd in the already running daemon, instead of running a specific one for warpd. I see this a particular case of the well known unix philosophy.

I would normally be inclined to agree but there are certain design considerations that warrant making warpd a daemon. Notably, since warpd is a mouse replacement it should be available all of the time. To this end it uses special xinput hacks to overcome the limitations of standard X grabs used by programs like xbindkeys which struggle under certain scenerios (e.g popup menus).

> Moreover, it would be great if the command line accepts an option to select the mode (hints, normal, etc)

There are already different activation keys you can set for each mode. What is your use case?

> Being able to specify the geometry rectangle would solve the xinerama issue in an obvious way, because we could use the keybinding daemon to use different options to launch warpd depending on which screen we are currently focused.

I would be more inclined to add proper multi screen support at this point. It shouldn't be too difficult, it's just that no one has bothered to complain :P.

**Comment by fboumol** [comment]
> 
> The early prototypes used to have such a 'oneshot' mode but they were replaced in favour of a dedicated daemon for a few reasons. The main one is that some of the drawing operations are expensive (especially hint mode) so running as a dedicated daemon allows warpd to cache some of them and and make it performant. It would be theoretically possible to retain some of these benfits by forking and adding some kind of IPC mechanism but this would add unecessary complexity.

I can see what you mean. Nevertheless, let me suggest (but feel free to ignore it) the possibility of considering the chance of launching it as a daemon and having one keybinding in the program for killing the daemon. This would be like my "oneshot" suggestion and would avoid the troubles you talk about.


> 
> > Moreover, it would be great if the command line accepts an option to select the mode (hints, normal, etc)
> 
> There are already different activation keys you can set for each mode. What is your use case?

I wasn't thinking in a unique case. My suggestion, combined with bash scripting, would give the chance to a lot of possibilities (depending on which screen of my xinerama display I would use one method or another, etc)

> 
> > Being able to specify the geometry rectangle would solve the xinerama issue in an obvious way, because we could use the keybinding daemon to use different options to launch warpd depending on which screen we are currently focused.
> 
> I would be more inclined to add proper multi screen support at this point. It shouldn't be too difficult, it's just that no one has bothered to complain :P.

I will not be the one complaining, as it is it is already great.

**Comment by rvaiya** [comment]
I believe what you want can be accomplished using `oneshot_button`. If not, feel free to open another issue. I am closing this for now.
