### ISSUE TITLE
Shouldn't let its shortcuts propagate to windows

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warpd#41]
I've been facing this issue more now, I don't know how i didn't notice it before. Whenever I click on something like a text box using warpd and then hit esc to exit it, sometimes it will also unfocus the text box depending on the application. I've also notice this on another keybindings that warpd is passing by its shortcuts instead of fully consuming them and not letting the focused window receive them.

Would that be easy to fix? Or maybe I am just missing something. Some other X applications do that, like dunst before they removed shortcuts from it. They do not let their shortcuts propagate. Well I hope that is understandable.

**Comment by rvaiya** [comment]
It depends on the shortcuts in question. Traditionally X grabs are used to avoid interference among multiple clients which want to listen for the same set of keys. warpd used to use these grabs before they were replaced by a custom input layer based on xinput in order to allow compatibility with more applications. 

While warpd is active it should grab all keys, but before it is active it has no way of preventing applications from processing the activation keys. It is up to the user to ensure there are no conflicts. This is why it is currently possible to bind activation keys which conflict with your window manager bindings.

Having said that, I am currently in the process of doing a partial rewrite (mainly to add macos support) which will likely end up using standard X grabs for the linux implementation.

**Comment by matheusfillipe** [comment]
Well the shortcut that most bothers me is esc. I dont mean the activation keys. On some programs I try to use warpd to focus on a text box but when I hit esc to exit warpd it also exits the textbox.

**Comment by matheusfillipe** [comment]
Actually seems this is only happening with the exit shortcut. Is there something specific to it that is making other applications grab it?

**Comment by matheusfillipe** [comment]
I just bisected and the problem was introduced by: 806f6a01e6684d758161f59cd6ac44fe5d1fa352 

It is the leaking exit key problem.

**Comment by matheusfillipe** [comment]
Changing that 0 to 1 fixes it for me. Maybe it has other consequences?
```
diff --git a/src/main.c b/src/main.c
index 348a72b..94809c5 100644
--- a/src/main.c
+++ b/src/main.c
@@ -440,7 +440,7 @@ void main_loop()
                }


-               input_ungrab_keyboard(0);
+               input_ungrab_keyboard(1);
                set_cursor_visibility(1);
        }
 }
```

**Comment by rvaiya** [comment]
Sorry, you're right. This is indeed a regression. I have fixed it in the latest commit. Note that I will be releasing a fairly major overhaul of the current code base in the next few days that will also include some design changes.
