### ISSUE TITLE
Buggy interaction with OS X native Sticky Keys

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warpd#43]
I use sticky keys (generic modifier oneshot and/or lock, basically) on OS X and it interact strangely with warpd – with a sticky key active that's used by my warpd config, warpd will behave correctly and the stickiness is cleared, but OSX's visual indicator of the sticky status stays around even though it is no longer active.

I've also encountered situations in which all input (Including mouse and keystrokes) become non-responsive (Sometimes to the point of requiring a hard reboot). I can provoke this with a sticky lock that is part of  a warpd activation key (ie,  C–S –. as warpd config, lock control, then press Shift + .)

You can enable sticky keys in System preferences  - Accessibility – keyboard. I can provide more details or a screen capture if it helps.

**Comment by rvaiya** [comment]
> I use sticky keys (generic modifier oneshot and/or lock, basically) on OS X and it interact strangely with warpd – with a sticky key active that's used by my warpd config, warpd will behave correctly and the stickiness is cleared, but OSX's visual indicator of the sticky status stays around even though it is no longer active.

This is probably because warpd absorbs the activation key, so it never gets reported to the operating system. It would be possible to change this behaviour by allowing the event to propagate, but that would introduce the possibility of conflicting keyboard shortcuts. My advice would be to disable visual notifications for sticky keys altogether. If this really bothers you, it might be possible to fix with a kludge, but it would only apply to transiently activated modifiers (i.e ones which have been tapped once).

> I've also encountered situations in which all input (Including mouse and keystrokes) become non-responsive (Sometimes to the point of requiring a hard reboot). I can provoke this with a sticky lock that is part of a warpd activation key (ie, C–S –. as warpd config, lock control, then press Shift + .)

warpd expects to receive bound keys in the exact state they are specified in the config.  With sticky keys it is easy to accidentally activate warpd with an active modifier which gets applied to all key sequences (especially with a broken visual indicator). This can be solved by deactivating the modifier and then pressing the exit key.

**Comment by wearpants** [comment]
> This is probably because warpd absorbs the activation key, so it never gets reported to the operating system. It would be possible to change this behaviour by allowing the event to propagate, but that would introduce the possibility of conflicting keyboard shortcuts.

Definitely don't want that.

> My advice would be to disable visual notifications for sticky keys altogether. If this really bothers you, it might be possible to fix with a kludge, but it would only apply to transiently activated modifiers (i.e ones which have been tapped once).

I tried this, and it's very hard to use without the visual indicator. Also not sure about what's going on in the hood - even though the indicator gets out of sync, the sticky modifier is correctly cleared... How is that happening if warpd is not passing through to the OS?

> warpd expects to receive bound keys in the exact state they are specified in the config. With sticky keys it is easy to accidentally activate warpd with an active modifier which gets applied to all key sequences (especially with a broken visual indicator). This can be solved by deactivating the modifier and then pressing the exit key.

Right but without Visual indicator it's hard to know whether modifiers active or not - I end up randomly mashing buttons, and sometimes this gets me out and sometimes seems to hard lock the display manager as described... in these situations, there's sometimes nothing on screen drawn by warpd (no grid or Mouse box) - can't tell if  there's another bug going on or not.

**Comment by rvaiya** [comment]
> even though the indicator gets out of sync, the sticky modifier is correctly
> cleared... How is that happening if warpd is not passing through to the OS?

It seems the visual indicator is handled higher up the stack. stickyness itself
seems to be baked into the low level input logic, but the visual indicator
seems to rely on events which get blocked before they reach the display server.

> Right but without Visual indicator it's hard to know whether modifiers active
> or not - I end up randomly mashing buttons, and sometimes this gets me out and
> sometimes seems to hard lock the display manager as described... in these
> situations, there's sometimes nothing on screen drawn by warpd (no grid or
> Mouse box) - can't tell if there's another bug going on or not.

A solution to this might be to clear the active modifier set before starting warpd.
This would still prohibit the use of sticky visual indicators while warpd is active,
but would put you in a known state upon initialization. I am a bit preoccupied at
the moment, will experiment with this soon.

**Comment by wearpants** [comment]
> A solution to this might be to clear the active modifier set before starting warpd. This would still prohibit the use of sticky visual indicators while warpd is active, but would put you in a known state upon initialization.

That seems like the right direction

**Comment by rvaiya** [comment]
As it turns out, clearing the modifier set is non trivial since the coregraphics API doesn't have a mechanism to synthesize the necessary events. However after going down a few rabbit holes I was able to figure out what makes the sticky indicators tick and whitelist the requisite events. The end result is that visual indicators should now work as expected while warpd is active.

**Comment by rvaiya** [comment]
I'm closing this for now. Feel free to reopen the issue if you feel it is unresolved.
