### ISSUE TITLE
Feature request: Add wayland support

### ISSUE THREAD

**Issue by Cadair** [rvaiya/warpd#54]
Warpd looks really useful to me when used in combination with a tiling window manager. However, I use sway so would need wayland support.

Thanks for the cool project!

**Comment by roland-rollo** [comment]
Yeah, I use sway with wayland only mode (without xorg-xwayland) and I'm so keyboard oriented that using keyboard as mouse would be bless for me.

**Comment by rvaiya** [comment]
I am not intimately familiar with wayland internals, but my understanding is that its input model might present some implementation challenges. I don't have the time or motivation for a full port at the moment, but I am willing to take a crack at it if this issue gets enough upvotes.

**Comment by proudmuslim-dev** [comment]
I'd love to see this get ported - I currently use tridactyl to replace my mouse in Firefox, and having a utility that could replace it system-wide would be a game changer. If you open Monero donations, I'd be more than happy to chip in :^)

**Comment by rvaiya** [comment]
After some additional research, it seems that wayland is ill equipped for a port. I was peripherally aware of the input problems, but it seems there is no way to draw onto the screen or absolutely position windows either :/. There are some non-standard extensions which *might* make a port possible on wlroots based compositors (i.e sway) but as far as I can tell, Gnome users are out of luck. I may end up proceeding anyway if there is enough interest. 

It would help to have a idea of what people are using.

**Comment by dsych** [comment]
Fedora 36 with Wayland + Nvidia. I am not at all versed in compositors, but maybe you can leverage XWayland?

**Comment by rvaiya** [comment]
@dsych 
 
By 'Fedora 36' I assume you mean with the stock DE (Gnome) which doesn't support the layer shell protocol.

>  but maybe you can leverage XWayland?

Unfortunately XWayland won't work. warpd relies on certain X behaviours (e.g shaped windows) which are not fully implemented by wayland's compatibility layer (since this would provide an easy way to bypass the security model). 

From what I can tell, fragmentation seems to be a major problem in the Wayland ecosystem, with most of the useful protocols being developed by wlroots and Gnome flat out refusing to adopt them. Sadly this makes implementing an entire class of third party software impossible :(.

**Comment by Cadair** [comment]
I know I use sway so this isn't exactly unbiased, but there are quite a lot of wayland compositors based on wlroots now. Not saying you are going to get the market share of Gnome but it would still be useful to a lot of people.

**Comment by rvaiya** [comment]
I was more referring to Gnome's obstinacy as documented [here] (https://gitlab.gnome.org/GNOME/mutter/-/issues/973) (and elsewhere). I'm not sure what is involved in the standardization process, but my impression is that Gnome has no intention of introducing support for most of the necessary protocols. 

Having said that, I am not opposed to a limited port given that sway seems to be reasonably popular amongst the niche input crowd, and will probably be my first port of call when I inevitably make the transition.

**Comment by roland-rollo** [comment]
I agree with @Cadair. Creating a proper implementation, sticking to the protocol specification has been the domain of the wlroots (sway) team from the beginning. Wlroots now tries to be not only a library for Sway, but for every window manager that uses it, trying to be what X.org is for environments based on it. There are plenty of wlroots-based window managers that are completely different from each other, from floating window managers to the popular and well-known tiled window managers. There's a compiz clone, an openbox clone, and others. KDE is only now catching up and from what I can see they are trying to move towards implementing various things similarly to wlroots, unlike Gnome.
Even if KDE with their Kwin, wanted to go with something completely different, rhere is a Kwin fork based on wlroots.
LXQt and XFCE are not planning their window managers and are looking at developing current window managers for Wayland. At this point, the only troublemaker is Gnome's Mutter.

**Comment by rvaiya** [comment]
> Wlroots now tries to be not only a library for Sway, but for every window manager that uses it, trying to be what X.org is for environments based on it.

Admirable though it may be, wlroots != wayland.

> KDE is only now catching up and from what I can see they are trying to...
> At this point, the only troublemaker is Gnome's Mutter...

Evidently we have different definitions of 'fragmentation' :P.

Due to popular demand, I have added experimental support for wlroots based compositors. There were a few hard limitations on what could ultimately be achieved (and other things which I was just too lazy to implement). 

I have a few ideas about how to potentially remedy some of these, but I probably won't have time to implement them for a few weeks.

See the man page for details.

**Comment by Cadair** [comment]
Thank you very much for adding wayland support! :heart:
