### ISSUE TITLE
WARNING: <some-key-combo> is not a valid code!

### ISSUE THREAD

**Issue by AndydeCleyre** [rvaiya/warpd#79]
Hello, and thanks!

I'm having trouble configuring some key combinations, as shown below.

```console
% warpd -l |& grep -Ei 'comma|control|alt|^[jkli]$'
i
leftcontrol
j
k
l
comma
leftalt
kpjpcomma
rightcontrol
rightalt
kpcomma
alterase
```
```console
% cat ~/.config/warpd/config
```
```yaml
activation_key: rightalt-rightcontrol-j
hint_activation_key: rightalt-rightcontrol-l
grid_activation_key: rightalt-rightcontrol-k

left: j
down: k
right: l
up: i

drag: space
```
```console
% warpd -f
Starting warpd: 1.0.3-beta
WARNING: rightalt-rightcontrol-j is not a valid code!
WARNING: rightalt-rightcontrol-l is not a valid code!
WARNING: rightalt-rightcontrol-k is not a valid code!
```

Similarly:
```console
% cat ~/.config/warpd/config
```
```yaml
activation_key: rightalt-comma-j
hint_activation_key: rightalt-comma-l
grid_activation_key: rightalt-comma-k

left: j
down: k
right: l
up: i

drag: space
```

```console
% warpd -f
Starting warpd: 1.0.3-beta
WARNING: rightalt-comma-j is not a valid code!
WARNING: rightalt-comma-l is not a valid code!
WARNING: rightalt-comma-k is not a valid code!
```

**Comment by rvaiya** [comment]
Like most other programs, warpd can only use modified sequences as activation keys E.G `C-A-comma`. Even if you could bind `rightalt+,+l` it would probably be a bad idea, since you are likely to accidentally hit `,` before `rightalt`, which would produce the sequence `,` `A-l`. If you are committed to the idea, you can still achieve something like this using an evdev based remapper which supports timeouts like [keyd](https://github.com/rvaiya/keyd) (shameless plug), though I would still advise against this.

See also:

https://github.com/rvaiya/keyd/issues/81#issuecomment-1003790533
https://github.com/rvaiya/keyd/blob/b04ce338daad9633b35762575c8576f3835288f6/docs/keyd.scdoc#L336

**Comment by AndydeCleyre** [comment]
Thanks! What's a "modified sequence?"

**Comment by rvaiya** [comment]
It just means a key stroke involving one or more modifiers. E.G `C-a`, `A-a`, `A-C-a`, etc.

**Comment by AndydeCleyre** [comment]
How can I tell that, e.g. `rightalt`+`comma`+`j` is *not* a modified sequence?

**Comment by rvaiya** [comment]
The first involves multiple non-[modifier](see https://en.wikipedia.org/wiki/Modifier_key) keys (`comma` and `j`). While the second involves two keys which emit the same modifier (alt/`A`). You should have encountered these sort of bindings in others programs at some point (i3/vim/most terminals/ides). In general, if you can bind the sequence in another program you should be able to bind it in warpd.

**Comment by AndydeCleyre** [comment]
OK. Shame about no double alt usage. FWIW in KDE Plasma there is a keyboard setting to have `leftshift`+`rightshift` trigger capslock (handy if you remap the capslock key).

So I'm getting that warpd valid combos have:
- exactly one non-modifier
- not: left AND right of the same modifier

**Comment by rvaiya** [comment]
> exactly one non-modifier
> not: left AND right of the same modifier

Correct. Most programs do the same thing, because the display server does not differentiate between left and right variants of the same modifiers. Some programs (i.e window managers) do some additional handling to make this possible. 

If you really want to achieve this (and have considered all of the implications) you can use keyd and do something like the following:

```
[altgr]
comma = layer(alt-comma)

[alt-comma]
l = M-A-x
k = M-A-g
j = M-A-c
```

Which will cause `rightalt+,+l` to send `meta+alt+x`, though I'm not sure why you would want a 3 key activation sequence. Personally, I do the following:

```
[main]
meta = overload(meta, M-A-c)
```

which allows me to start keyd with a single keystroke, while preserving the behaviour of my meta key.
