### ISSUE TITLE
Input in iTerm

### ISSUE THREAD

**Issue by benvallack** [rvaiya/warpd#82]
I can't get warpd to work inside iTerm. i.e even if I run it from Terminal it still doesn't work when I'm in iTerm. Is it possible to get this to work?

**Comment by rvaiya** [comment]
Can you clarify what you mean by 'doesn't work'? Once you start the daemon it should work across all applications. There is a known bug in iTerm which causes the pointer to be visible when warpd is active, but it should otherwise work as expected. Are you suggesting you can activate it (`A-M-x`) in other applications, but not in iTerm?

**Comment by benvallack** [comment]
Yeah, nothing shows up in either iTerm or Terminal when I use the hot key triggers. It works as soon is switch to a non-terminal app.

**Comment by benvallack** [comment]
Ah no it is working fine in Terminal, the issue is just with iTerm. The hot keys just don'k work when I'm in iTerm, that is if I start warpd from iTerm or from Terminal. I will check if there are some conflicting hot keys somewhere.

**Comment by benvallack** [comment]
Ah! It is 'secure keyboard entry' mode in iTerm. Disabling that lets it all work fine.

**Comment by rvaiya** [comment]
Thanks for closing the loop. I'm closing this issue for now.
