### ISSUE TITLE
Switch to grid from normal mode behaviour

### ISSUE THREAD

**Issue by benvallack** [rvaiya/warpd#84]
When switching to grid mode from normal (after placing cursor with hint mode) the grid re-positions the cursor to the center. Is it possible to have the grid start centered at the cursor position when switched on while normal mode active. Ideally with an option to have the grid start smaller in this mode too. 

This would enable a great way of refining the position after a hint mode placement. If you place the cursor with the hint then immediately see the grid mode at the size of one of the hint zones, you could quickly use the grid to refine in to the target without battling with the normal mode direction keys. 

This is a very exciting project by the way - kudos!

**Comment by rvaiya** [comment]
I thought about doing something like this early on, but I've found hint mode in conjunction with the movement keys sufficient for quickly pinpointing most things on screen. The grid and hint modes are only intended for macroscopic movement to facilitate quick warping to the proximate region of interest, at which point normal mode can be used to make any adjustments. I'm not convinced there is room for an intermediate movement mode, but I am open to persuasion on the point if your experience suggests otherwise.

Incidentally, I rarely use grid mode in practice, it only exists because warpd originally started as a small C program to add a visual dimension to the quadrant based warping found in the keyboardio firmware. The person for whom it was originally developed uses some unorthodox hardware, so it has mainly been retained for backward compatibility, though I personally find hints to be much more efficient.

My usual pattern is to warp to a hint, make any necessary adjustments, and click. I find that about 70% of the time I don't need to make any adjustments, and when I do, it usually consists of one or two taps of the movement keys.

P.S

I thought your name looked familiar, it would seem we are both afflicted by the same input bug. It turns out I've recently enjoyed some of your content, so this feels like a serendipitous encounter :P.

**Comment by benvallack** [comment]
Ok this sounds good I will keep familiarising myself with the direction keys for final adjustment. I may try adding some more characters to the hint grid to increase resolution too.

Thanks - someone actually emailed me to recommend warpd, so glad they did, I've been looking for something like this for a while.

I'm sure it won't be long before I include this in a video if that's all ok with you!

Cheers
Ben

**Comment by rvaiya** [comment]
> Ok this sounds good I will keep familiarising myself with the direction keys for final adjustment. I may try adding some more characters to the hint grid to increase resolution too.

You may also want to fiddle with `max_speed` and `acceleration`. I picked defaults which work well on my machine, but if you find normal movement cumbersome for short distances you may need to adjust them.

> I'm sure it won't be long before I include this in a video if that's all ok with you!

Sounds good :). I've been thinking about making a video to provide a better idea of what real world warpd usage looks like, so this would be quite helpful. I should note that the program still has several warts, some of which exist for legacy/implementation reason. I've recently invested some more time into the project given the influx of interest, but the macOS port is not my daily driver (and relatively new), so it is inclined to have a few more bugs. Feel free to open an issue or email me if you have any questions.

**Comment by rvaiya** [comment]
I'm closing this for now, but feel free to reopen it if you still feel strongly about it.
